<a href="https://colab.research.google.com/github/suran20/-Data_visualization_PCA2/blob/main/SuranjanaDey_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. CREATING A LIST AND PERFORMING THE FOLLOWING

In [ ]:
# a)insert()

l=[12,40,88,75,15]
l.insert(2,35)
print(l)

[12, 40, 35, 88, 75, 15]


In [ ]:
# b)remove()

l.remove(75)
print(l)

[12, 40, 35, 88, 15]


In [ ]:
# c)append

l.append(67)
print(l)

[12, 40, 35, 88, 15, 67]


In [ ]:
# d)length

len(l)

0

In [ ]:
# e)pop

a=l.pop(1)
print(a)

40


In [ ]:
# f)clear

l.clear()
print(l)

[]


2. ENTERING THE MARKS OF 5 SUBJECTS AND DISPLAYING THE GRADE

In [ ]:
marks1 = 67
marks2 = 78
marks3 = 92
marks4 = 67
marks5 = 83

In [ ]:
sum_marks=marks1+marks2+marks3+marks4+marks5
avgmark=sum_marks/5

In [ ]:
if (avgmark>=90):
 print("Average of 5 marks=",avg,"Grade=A")
elif(avgmark>=80 and avgmark<90):
 print("Average of 5 marks=",avg,"Grade=B")
elif(avgmark>=70 and avgmark<80):
 print("Average of 5 marks=",avg,"Grade=C")
elif(avgmark>=60 and avgmark<70):
 print("Average of 5 marks=",avg,"Grade=D")
elif(avgmark>=50 and avgmark<60):
 print("Average of 5 marks=",avg,"Grade=E")

Average of 5 marks= 77.4 Grade=C


3. REVERSING A GIVEN NUMBER


In [ ]:
num=6523
rev=0
while num!=0:
  digit=num%10
  rev=rev*10+digit
  num=num//10

print ("Reversed Number:", rev)

Reversed Number: 3256


4. READING A NUMBER AND COMPUTING

In [ ]:
n=int(input("Enter a value for n:"))
m=int(input("Enter a value for m:"))
temp=n
sum=0
for i in range (m):
  sum+=temp
  temp=temp*10+n
print(sum)

Enter a value for n:5
Enter a value for m:5
61725


5. PRINTING DATE TIME FOR TODAY AND NOW

In [ ]:
import datetime
now=datetime.datetime.now()
print("Current date and time: ")
print(str(now))

Current date and time: 
2022-12-15 15:51:30.357125


6. CREATING NUMPY MODULE AND PERFORMING OPERATIONS

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[4,6,8,9,10]])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print("No. of dimensions : ", arr.ndim)

No. of dimensions :  2


In [ ]:
print(arr.shape)

(2, 5)


In [ ]:
# d) Type of elements in array
#0-D Array
import numpy as np
arr = np.array(62)
print(arr)

62


In [ ]:
#1-D Array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
#2-D Array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3-D Array
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
